- name: Setting up swap space
  include: swap.yml
  tags:
    - swap
- name: Installing prerequisite packages
  apt:
    name:
      - socat
      - netcat-openbsd
      - python3
      - openjdk-11-jre
      - supervisor
    state: latest
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - packages
- name: Setting up accounts
  include: accounts.yml
  tags:
    - accounts
- name: Setting up Minecraft server
  include: server.yml
  tags:
    - server
- name: Setting up supervisor
  include: supervisor.yml
  tags:
    - supervisor
