- name: Provision Minecraft server
  hosts: minecraft
  gather_facts: no
  become: yes
  vars_files:
    - config.yml
  roles:
    - name: provision
      tags:
        - provision
    - name: config
      tags:
        - config
    - name: plugins
      tags:
        - plugins
